robot2:
  footprint:
      {
       front_left_x: 1.9,
       front_left_y: 0.3,
       front_right_x: 1.9,
       front_right_y: -0.3,
       rear_left_x: -0.2,
       rear_left_y: 0.3,
       rear_right_x: -0.2,
       rear_right_y: -0.3
      }
  controller:
      {
       robot_id: 2
      }
  tf_prefix:
      robot2
  euro_pallet_sdf_node:
      {
       depth_frame_id: robot2/asus_fork_rgb_optical_frame,
      }
  orunav_vehicle_execution_node:
    {
     robot_id: 2,
     safety_laser_topic: /sensors/laser2d_floor,
     safety_laser_topic2: /sensors/laser2d_top
    }
  euro_pallet_sdf_node:
     robot_id: 2
  vehicle_client:
     robot_id: 2
  coordination:
     rosduct:
        local_services:
        - [/robot2/compute_task, orunav_msgs/ComputeTask]
        - [/robot2/execute_task, orunav_msgs/ExecuteTask]
        - [/robot2/set_task, orunav_msgs/SetTask]
        - [/robot2/next_task, std_srvs/Empty]
        local_topics:
        - [/robot2/report, orunav_msgs/RobotReport]
        - [/robot2/control/controller/cmd_vel, geometry_msgs/Twist]
        # for rviz
        - [/robot2/visualization_marker, visualization_msgs/Marker]
        remote_services: []
        remote_topics:
        - [/active_robots, orunav_msgs/ActiveRobots]
        # from map server
        - [/maps/map_laser2d, nav_msgs/OccupancyGrid]
        - [/maps/map_metadata, nav_msgs/MapMetaData]
        # from Gazebo...
        - [/clock, rosgraph_msgs/Clock]
        - [/gazebo/link_states, gazebo_msgs/LinkStates]
        - [/robot2/joint_states, sensor_msgs/JointState]
        - [/robot2/odom, nav_msgs/Odometry]
        - [/robot2/odom_enc, nav_msgs/Odometry]
        - [/robot2/sensors/laser2d_floor, sensor_msgs/LaserScan]
        - [/robot2/sensors/laser2d_top, sensor_msgs/LaserScan]
