robot4:
    footprint:
        front_left_x: 1.9
        front_left_y: 0.3
        front_right_x: 1.9
        front_right_y: -0.3
        rear_left_x: -0.2
        rear_left_y: 0.3
        rear_right_x: -0.2
        rear_right_y: -0.3
  tf_prefix:
       robot4
  euro_pallet_sdf_node:
      {
       depth_frame_id: robot4/asus_fork_rgb_optical_frame,
      }
  euro_pallet_sdf_node:
     robot_id: 4
  vehicle_client:
     robot_id: 4
  coordination:
     rosduct:
        local_services:
        - [/robot4/compute_task, orunav_msgs/ComputeTask]
        - [/robot4/execute_task, orunav_msgs/ExecuteTask]
        - [/robot4/set_task, orunav_msgs/SetTask]
        - [/robot4/next_task, std_srvs/Empty]
        local_topics:
        - [/robot4/report, orunav_msgs/RobotReport]
        - [/robot4/control/controller/cmd_vel, geometry_msgs/Twist]
        # for rviz
        - [/robot4/visualization_marker, visualization_msgs/Marker]
        remote_services: []
        remote_topics:
        # this one only for uol...
        - [/robot4/goal,  geometry_msgs/PoseStamped]
        - [/active_robots, orunav_msgs/ActiveRobots]
        # from map server
        - [/maps/map_laser2d, nav_msgs/OccupancyGrid]
        - [/maps/map_metadata, nav_msgs/MapMetaData]
        # from Gazebo...
        - [/clock, rosgraph_msgs/Clock]
        - [/gazebo/link_states, gazebo_msgs/LinkStates]
        - [/robot4/joint_states, sensor_msgs/JointState]
        - [/robot4/odom, nav_msgs/Odometry]
        - [/robot4/odom_enc, nav_msgs/Odometry]
        - [/robot4/sensors/laser2d_floor, sensor_msgs/LaserScan]
        - [/robot4/sensors/laser2d_top, sensor_msgs/LaserScan]
        - [/robot4/sensors/kinect2/depth/camera_info, sensor_msgs/CameraInfo]
        - [/robot4/sensors/kinect2/hd/camera_info, sensor_msgs/CameraInfo]
        - [/robot4/sensors/kinect2/hd/image_color_rect, sensor_msgs/Image]
        - [/robot4/sensors/kinect2/hd/image_color_rect/compressed, sensor_msgs/CompressedImage]
        - [/robot4/sensors/kinect2/hd/image_color_rect/compressed/parameter_descriptions,
          dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/hd/image_color_rect/compressed/parameter_updates, dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/hd/image_color_rect/compressedDepth, sensor_msgs/CompressedImage]
        - [/robot4/sensors/kinect2/hd/image_color_rect/compressedDepth/parameter_descriptions,
          dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/hd/iage_color_rect/compressedDepth/parameter_updates,
          dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/parameter_descriptions, dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/parameter_updates, dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/sd/camera_info, sensor_msgs/CameraInfo]
        - [/robot4/sensors/kinect2/sd/image_depth_rect, sensor_msgs/Image]
        - [/robot4/sensors/kinect2/sd/image_ir_rect, sensor_msgs/Image]
        - [/robot4/sensors/kinect2/sd/image_ir_rect/compressed, sensor_msgs/CompressedImage]
        - [/robot4/sensors/kinect2/sd/image_ir_rect/compressed/parameter_descriptions,
          dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/sd/image_ir_rect/compressed/parameter_updates, dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/sd/image_ir_rect/compressedDepth, sensor_msgs/CompressedImage]
        - [/robot4/sensors/kinect2/sd/image_ir_rect/compressedDepth/parameter_descriptions,
          dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/sd/image_ir_rect/compressedDepth/parameter_updates,
          dynamic_reconfigure/ConfigDescription]
        - [/robot4/sensors/kinect2/sd/points, sensor_msgs/PointCloud2]
        - [/robot4/sensors/velodyne/velodyne_points, sensor_msgs/PointCloud2]
